plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.loan-microservice'
version = '0.0.1-SNAPSHOT'
description = 'This service saves the data about de loans'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// 1. Framework & Drivers
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
	runtimeOnly 'org.postgresql:postgresql'
	runtimeOnly 'org.postgresql:r2dbc-postgresql'

	// 2. Lombok (Debe ir PRIMERO en los procesadores)
	compileOnly 'org.projectlombok:lombok:1.18.30'
	annotationProcessor 'org.projectlombok:lombok:1.18.30'

	// 3. MapStruct Binding (El "pegamento" entre ambos)
	// Se coloca aquí para asegurar que Lombok y MapStruct se hablen bien
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	// 4. MapStruct (Debe ir DESPUÉS de Lombok)
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

	// 5. Testing
	testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-r2dbc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Opcional: Si usas Lombok en tests
	testCompileOnly 'org.projectlombok:lombok:1.18.30'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
}

tasks.named('test') {
	useJUnitPlatform()
}
